- name: "{{ user_id }} Check if user exists"
  shell: id -u "{{ user_id }}"
  register: user_exists
  ignore_errors: true
  
- name: "{{ user_id }} Change password"
  user:
    name: :{{ user_id }}"
    password: "{{ (first_password_var + lastname + second_password_var) | password_hash('sha512') }}"
  when:
  - user_exists.rc == 0
